name: cupertino_icons

description: Default icons asset for Cupertino widgets
author: Flutter Team <flutter-dev@googlegroups.com>
homepage: https://github.com/flutter/cupertino_icons
version: 0.1.2

flutter:
  fonts:
    - family: CupertinoIcons
      fonts:
        - asset: assets/CupertinoIcons.ttf
